name: Add a review
description: Submit a review to be added to the site!
title: Add a review
labels:
  - Review 🤔
assignees:
  - lbannana
body:
  - type: input
    attributes:
      label: Name
      description: Your review name
      placeholder: I hate nige
    validations:
      required: true
  - type: comfortaa
